_wandb:
    value:
        cli_version: 0.22.1
        e:
            be59q51xhby5kjkmk64qr8wdry0jln1i:
                codePath: 2st homework\hw1_1.ipynb
                codePathLocal: hw1_1.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "511192330240"
                        used: "388275486720"
                email: as990412@naver.com
                executable: c:\Users\as990\anaconda3\envs\link_dl\python.exe
                git:
                    commit: 16d0ae523d1ecb82bc83c45f5d3fd13954767ec3
                    remote: https://github.com/DREAMHAPPYLIFEJH/DeepLearning-Class.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-72f729f6-5641-de27-b6fc-c5694e1115e6
                host: LeeJihoon
                memory:
                    total: "16440479744"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\as990\link_dl\_04_your_code\2st homework\hw1_1.ipynb
                python: CPython 3.10.18
                root: c:\Users\as990\link_dl\_04_your_code\2st homework
                startedAt: "2025-10-01T11:59:00.038356Z"
                writerId: be59q51xhby5kjkmk64qr8wdry0jln1i
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.10.18
            "5": 0.22.1
            "8":
                - 1
                - 3
            "12": 0.22.1
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 2000
learning_rate:
    value: 0.001
n_hidden_unit_list:
    value:
        - 20
        - 20
